# Netlify 自动部署配置文件
# 适用于 Next.js 项目的 GitHub 集成部署

[build]
  # 发布目录 - Next.js 构建输出
  publish = ".next"
  
  # 构建命令
  command = "npm ci && npm run build"
  
  # 构建环境设置
  [build.environment]
    NODE_VERSION = "18"
    NPM_FLAGS = "--prefix=/opt/buildhome/.nodejs --global"

# 页面重定向配置 - 支持 Next.js 客户端路由
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# API 路由重定向（如果有的话）
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# 构建钩子 - GitHub 推送时自动触发
[build.processing]
  skip_processing = false

# 环境变量提示（实际配置在 Netlify Dashboard 中）
# NEXT_PUBLIC_SUPABASE_URL=https://mdnkzndpcmgoasmxgrxt.supabase.co
# NEXT_PUBLIC_SUPABASE_ANON_KEY=your_supabase_anon_key_here
